//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yamed_Terminal_Service_GetPatient.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEOPLE
    {
        public string FAM { get; set; }
        public string IM { get; set; }
        public string OT { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<System.DateTime> DR { get; set; }
        public string CN { get; set; }
        public Nullable<System.DateTime> DS { get; set; }
        public string RN { get; set; }
        public string INDX { get; set; }
        public string RNNAME { get; set; }
        public string CITY { get; set; }
        public string NP { get; set; }
        public string UL { get; set; }
        public string DOM { get; set; }
        public string KOR { get; set; }
        public string KV { get; set; }
        public string Q { get; set; }
        public string SPOL { get; set; }
        public string NPOL { get; set; }
        public string ENP { get; set; }
        public Nullable<int> OPDOC { get; set; }
        public Nullable<System.DateTime> DBEG { get; set; }
        public Nullable<System.DateTime> DEND { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> DSTOP { get; set; }
        public string DOCTP { get; set; }
        public string DOCS { get; set; }
        public string DOCN { get; set; }
        public string MR { get; set; }
    }
}
